//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YarraGo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Review
    {
        public int Id { get; set; }
        public string Rating { get; set; }
        [Required]
        [AllowHtml]
        public string Comment { get; set; }
        public int CustomerId { get; set; }
        public int CruiseId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Cruise Cruise { get; set; }
    }
}
